stages:
  - build_and_test

build:nightly:
  stage: build_and_test
  script:
    - apt-get update
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    - source $HOME/.cargo/env
    - rustup component add clippy-preview
    - cargo build --features integration-test --all-targets
    - cargo build --features integration-test --all-targets --release
    - mkdir /sys/fs/cgroup/{cpuacct,memory,pids}/ia-sandbox
    - cargo test -v
    - cargo clippy --all-targets
