language: rust
cache:
  directories:
    - $HOME/.cargo
sudo: required
dist: trusty
os:
  - linux

rust:
  - nightly

env:
  - RUST_BACKTRACE=full

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

before_install:
  - sudo apt-get update
  - sudo mkdir /sys/fs/cgroup/cpuacct/ia-sandbox
  - sudo mkdir /sys/fs/cgroup/memory/ia-sandbox
  - sudo chown -R $(id -u):$(id -g) /sys/fs/cgroup/cpuacct/ia-sandbox
  - sudo chown -R $(id -u):$(id -g) /sys/fs/cgroup/memory/ia-sandbox

script:
  - cargo build --all-targets --features "integration-test"
  - cargo build --release --bins --features "integration-test"
  - cargo test -- --test-threads 1

 # Coverage report
after_success:
  - ./.coverage.sh
