language: rust
cache:
  directories:
    - $HOME/.cargo
sudo: required
dist: trusty
os:
  - linux

rust:
  - nightly

env:
  - RUST_BACKTRACE=full

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

before_install:
  - sudo apt-get update

script:
  - cargo build --all-targets
  - cargo test

 # Coverage report
after_success:
  - ./.coverage.sh
